import { Category } from "@enums/category.enum";
import { Pizza } from "@interfaces/menu.interface";

export const pizzas: Pizza[] = [
  {
    id: 1,
    name: "Margarita",
    category: Category.PIZZA,
    ingredients: [2, 3, 25],
    price: 10.0,
    description: "",
    special: false,
    allergens: [8],
  },
  {
    id: 2,
    name: "Funghi",
    category: Category.PIZZA,
    ingredients: [2, 3, 24, 25],
    price: 11.0,
    description: "",
    special: false,
    allergens: [8],
  },
  {
    id: 3,
    name: "Prosciutto",
    category: Category.PIZZA,
    ingredients: [2, 3, 5, 25],
    price: 12.0,
    description: "",
    special: false,
    allergens: [8],
  },
  {
    id: 4,
    name: "Prosciutto e funghi",
    category: Category.PIZZA,
    ingredients: [2, 3, 5, 24, 25],
    price: 13.0,
    description: "",
    special: false,
    allergens: [8],
  },
  {
    id: 5,
    name: "Peperoni",
    category: Category.PIZZA,
    ingredients: [2, 3, 26, 25],
    price: 13.5,
    description: "",
    special: false,
    allergens: [8],
  },
  {
    id: 6,
    name: "Pugliese",
    category: Category.PIZZA,
    ingredients: [2, 3, 26, 27, 28, 25],
    price: 13.5,
    description: "",
    special: false,
    allergens: [8],
  },
  {
    id: 7,
    name: "Sienna",
    category: Category.PIZZA,
    ingredients: [2, 3, 5, 26, 27, 25],
    price: 13.5,
    description: "",
    special: false,
    allergens: [8],
  },
  {
    id: 8,
    name: "Beicon y Cebolla",
    category: Category.PIZZA,
    ingredients: [2, 3, 15, 27, 25],
    price: 13.5,
    description: "",
    special: false,
    allergens: [4, 8],
  },
  {
    id: 9,
    name: "Carbonara",
    category: Category.PIZZA,
    ingredients: [2, 3, 15, 29, 25],
    price: 13.5,
    description: "",
    special: false,
    allergens: [4, 8],
  },
  {
    id: 10,
    name: "Napolitana",
    category: Category.PIZZA,
    ingredients: [2, 3, 15, 29, 25],
    price: 14.0,
    description: "",
    special: false,
    allergens: [4, 8],
  },
  {
    id: 11,
    name: "Salmon",
    category: Category.PIZZA,
    ingredients: [2, 3, 4, 6, 25],
    price: 14.0,
    description: "",
    special: false,
    allergens: [2, 8],
  },
  {
    id: 12,
    name: "Quattro Stagioni",
    category: Category.PIZZA,
    ingredients: [2, 3, 5, 24, 30, 31, 25],
    price: 14.0,
    description: "",
    special: false,
    allergens: [8],
  },
  {
    id: 13,
    name: "Quattro Formaggi",
    category: Category.PIZZA,
    ingredients: [2, 3, 8, 25],
    price: 14.0,
    description: "",
    special: false,
    allergens: [8],
  },
  {
    id: 14,
    name: "Pesto",
    category: Category.PIZZA,
    ingredients: [2, 3, 40, 25],
    price: 14.0,
    description: "",
    special: false,
    allergens: [8, 12],
  },
  {
    id: 15,
    name: "Hawaiana",
    category: Category.PIZZA,
    ingredients: [2, 3, 5, 32, 25],
    price: 13.5,
    description: "",
    special: false,
    allergens: [8],
  },
  {
    id: 16,
    name: "Capricciosa",
    category: Category.PIZZA,
    ingredients: [2, 3, 25],
    price: 14.0,
    description: "",
    special: false,
    allergens: [8],
  },
  {
    id: 17,
    name: "Rúcula y Parmigiano",
    category: Category.PIZZA,
    ingredients: [2, 3, 33, 34, 20, 25],
    price: 14.0,
    description: "",
    special: false,
    allergens: [8],
  },
  {
    id: 18,
    name: "Caprese",
    category: Category.PIZZA,
    ingredients: [2, 3, 39, 35, 34, 25],
    price: 13.5,
    description: "",
    special: false,
    allergens: [8],
  },
  {
    id: 19,
    name: "Tonno",
    category: Category.PIZZA,
    ingredients: [2, 3, 36, 27, 25],
    price: 13.5,
    description: "",
    special: false,
    allergens: [2, 8],
  },
  {
    id: 20,
    name: "Barbacoa",
    category: Category.PIZZA,
    ingredients: [2, 3, 14, 37, 25],
    price: 14.0,
    description: "",
    special: false,
    allergens: [8],
  },
  {
    id: 21,
    name: "Capri",
    category: Category.PIZZA,
    ingredients: [37, 3, 23, 38, 39],
    price: 14.0,
    description: "",
    special: false,
    allergens: [8],
  },
  {
    id: 22,
    name: "Kiko",
    category: Category.PIZZA,
    ingredients: [38, 3, 23, 24],
    price: 14.0,
    description: "",
    special: true,
    allergens: [8],
  },
];
